using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.IO;
using System.Text.RegularExpressions;
using DotSmart.LessCoffee;
using DotSmart.Properties;
using System.Diagnostics;

namespace DotSmart
{
    public class LessCssHandler : ScriptHandlerBase
    {

        static string _lessc;

        /// <summary>
        /// Initializes a new instance of the LessCssHandler class.
        /// </summary>
        static LessCssHandler()
        {
            _lessc = Path.Combine(TempDirectory, @"node_modules\less\bin\lessc");
        }

        protected override string ContentType
        {
            get { return "text/css"; }
        }

        protected override void Render(string physicalFileName, TextWriter output)
        {
            output.Write("/* Generated by DotSmart LessCoffee on " + DateTime.Now + " - http://dotsmart.net */ \r\n");
            output.Write("/* Using LESS - Leaner CSS - http://lesscss.org - Copyright (c) 2009-2012, Alexis Sellier */ \r\n\r\n");

            renderStylesheet(physicalFileName, output);
        }

        protected override IEnumerable<string> GetFileDependencies(string physicalFileName)
        {
            // look for "@import" and add those to dependencies also
            return parseImports(physicalFileName);
        }

        static IEnumerable<string> parseImports(string lessFileName)
        {
            string dir = Path.GetDirectoryName(lessFileName);

            var importRegex = new Regex(@"@import\s+[""'](.*)[""'];");

            return (from line in File.ReadAllLines(lessFileName)
                    let match = importRegex.Match(line)
                    let file = match.Groups[1].Value
                    where match.Success
                      && !file.EndsWith(".css", StringComparison.OrdinalIgnoreCase)
                    select Path.Combine(dir, Path.ChangeExtension(file, ".less"))
            );
        }

        internal static bool renderStylesheet(string lessFilePath, TextWriter output)
        {
            try
            {
                string postscript = null;
                if (GetPostscript != null)
                    postscript = GetPostscript.GetInvocationList().Cast<Func<string, string>>().Select(func => func(lessFilePath)).Join(Environment.NewLine);

                RenderCss(lessFilePath, output, compress: !DebugMode, lessPostscript: postscript);
                return true;
            }
            catch (Exception ex)
            {
                output.WriteLine("/* ERROR: " + ex.Message + " */");
                return false;
            }
        }

        /// <summary>
        /// Here you can dynamically append extra bits of LESS script at 
        /// runtime e.g. variable overrides. For example you could grab 
        /// user's favourite colour from database.
        /// </summary>
        public static event Func<string, string> GetPostscript;

        public static void RenderCss(string lessFilePath, TextWriter output, bool compress = true, string lessPrologue = null, string lessPostscript = null)
        {
            TextReader lessStream;

            string lessSrc = File.ReadAllText(lessFilePath);
            lessStream = new StringReader(
                lessPrologue
                + lessSrc
                + lessPostscript
                );

            using (lessStream)
            using (var errors = new StringWriter())
            {
                string dirname = Path.GetDirectoryName(lessFilePath);
                if (dirname.Contains(' '))
                    throw new ApplicationException("lessc doesn't support file paths with spaces");

                string args = "\"" + _lessc + "\""
                    + " -" // read from stdin
                    + (compress ? " --yui-compress" : "")
                    + " --include-path=" + dirname
                    + " --no-color";
                int exitCode = ProcessUtil.Exec(NodeExe,
                    args: args,
                    stdIn: lessStream,
                    stdOut: output,
                    stdErr: errors);
                if (exitCode != 0)
                {
                    throw new ApplicationException(string.Format("Error {0} in '{1}': \r\n{2}",
                                                    exitCode,
                                                    lessFilePath,
                                                    errors.ToString().Trim()));
                }
            }
        }

    }
}
